print("What is your name?")
nameUser = str(input())
print("How old are you?")
oldUser = int(input())
print("Where are you live?")
liveUser = str(input())
print("This is", nameUser)
print("It is", oldUser)
print("(S)he live in", liveUser)
